[package]
name = "bottlerocket-agents"
version = "0.1.0"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
agent-common = { path = "../../agent/agent-common" }
bottlerocket-types = { path = "../types" }
async-trait = "0.1"
aws-config = "0.11"
aws-types = "0.11"
aws-sdk-ec2 = "0.11"
aws-sdk-ecs = "0.11"
aws-sdk-eks = "0.11"
aws-sdk-iam = "0.11"
aws-sdk-ssm = "0.11"
aws-sdk-sts = "0.11"
aws-smithy-types = "0.41"
base64 = "0.13.0"
env_logger = "0.9"
hex ="0.4.3"
k8s-openapi = { version = "0.14", default-features = false, features = ["v1_20"] }
kube = { version = "0.71", default-features = false, features = ["config", "derive", "client"] }
log = "0.4"
maplit = "1.0.2"
model = { path = "../../model" }
reqwest = { version = "0.11.1", default-features = false, features = ["rustls-tls", "blocking"] }
resource-agent = { path = "../../agent/resource-agent" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
sha2 = "0.10"
snafu = "0.7"
test-agent = { path = "../../agent/test-agent" }
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
tough = { version = "0.12", features = ["http"] }
url = "2.2"
uuid = { version = "1.2", default-features = false, features = ["serde", "v4"] }

[build-dependencies]
yamlgen = { path = "../../yamlgen" }
